import type { Idea } from "./schema";

export function ideaToMarkdown(idea: Idea, vibe: string): string {
  const lines: string[] = [];
  lines.push(`# ${idea.title}`);
  lines.push(``);
  lines.push(`> ${idea.premise}`);
  lines.push(``);
  lines.push(`_Vibe: ${vibe} · Generated by Give Me a Vibe_`);
  lines.push(``);
  for (const s of idea.sections) {
    lines.push(`## ${s.title}`);
    lines.push(``);
    lines.push(s.body);
    lines.push(``);
    if (s.bullets?.length) {
      for (const b of s.bullets) lines.push(`- ${b}`);
      lines.push(``);
    }
  }
  lines.push(`## Verdict`);
  lines.push(``);
  lines.push(`**${idea.verdict.summary}**`);
  lines.push(``);
  lines.push(idea.verdict.reasoning);
  lines.push(``);
  if (idea.metadata) {
    const bits = [
      idea.metadata.buildDifficulty && `Build: ${idea.metadata.buildDifficulty}`,
      idea.metadata.potential && `Potential: ${idea.metadata.potential}`,
      idea.metadata.nonsenseLevel && `Nonsense: ${idea.metadata.nonsenseLevel}`,
    ].filter(Boolean);
    if (bits.length) {
      lines.push(`---`);
      lines.push(bits.join(" · "));
      lines.push(``);
    }
  }
  if (idea.tags?.length) lines.push(`_${idea.tags.map((t) => `#${t}`).join(" ")}_`);
  return lines.join("\n").replace(/\n{3,}/g, "\n\n").trim() + "\n";
}

export function shareText(idea: Idea): string {
  return `${idea.title}\n${idea.premise}\n\nVerdict: ${idea.verdict.summary}\n\n— via Give Me a Vibe`;
}
